export const words: string[] = [
  "absolutny", "aktywny", "ambitny", "analityk", "ananas", "arbuz", "archiwum",
  "artysta", "atrakcyjny", "autobus", "autor", "balon", "banan", "barwa",
  "bazowy", "bezpieczny", "biblioteka", "biedny", "bilet", "bliski", "bogaty",
  "bohater", "bokser", "bratni", "brzydki", "budynek", "butelka", "bystry",
  "cieply", "ciekawy", "cukierek", "czapka", "czysty", "czytelnik", "dziecko",
  "dziennik", "dzwonek", "dokladny", "domowy", "doskonaly", "drozdzowy", "duchowy",
  "dumny", "dzielny", "dziewczyna", "ekonomiczny", "elektronika", "elita",
  "energiczny", "fabryka", "fajny", "fantazja", "farba", "filozofia", "filmowy",
  "flaga", "forma", "fotografia", "francuski", "futbol", "gabinet", "galeria",
  "gazeta", "genialny", "geografia", "gitarzysta", "glodny", "godny", "gornik",
  "goracy", "goscinny", "granica", "gratulacje", "grozny", "gruby", "gryf",
  "handel", "harmonia", "heroiczny", "historia", "hobby", "hotel", "humor",
  "idealny", "igielka", "internet", "informatyk", "instruktor", "intensywny",
  "jablko", "jakosc", "jasny", "jednostka", "jezioro", "kalendarz", "kamera",
  "kapitan", "kariera", "kasztan", "katastrofa", "klasa", "klient", "klocki",
  "kolorowy", "kolejny", "komedia", "komputer", "koncert", "konkurs", "kontakt",
  "kontrola", "korzystny", "kosciol", "kosmos", "kotek", "kowal", "kraina",
  "kreatywny", "kredyt", "kreskowka", "krowa", "krzywy", "ksiadz", "ksiazka",
  "kultura", "ladny", "latwy", "lekarz", "lekki", "lodowka", "logiczny",
  "losowy", "lozka", "malarz", "malpa", "marzenie", "maszyna", "matematyka",
  "medycyna", "miecz", "miejski", "mieszkanie", "milosc", "milutki", "mocny",
  "modelka", "modny", "morze", "motyl", "muzyka", "mysliwy", "mystery",
  "nagroda", "naukowy", "naturalny", "nauczyciel", "neuron", "niebieski",
  "niezly", "nocny", "normalny", "nowoczesny", "numer", "obiekt", "obowiazek",
  "odwaga", "ogorek", "ogromny", "ojciec", "okres", "okropny", "opinia",
  "optimum", "organizacja", "osiedle", "osoba", "ostry", "paczka", "pamiatka",
  "papier", "parasol", "pasja", "pejzaz", "pelny", "piasek", "piesek",
  "pilot", "piramida", "pisarz", "plakat", "planeta", "plecak", "plotka",
  "poczatek", "podroz", "pogoda", "pokoj", "pomocny", "poniedzialek",
  "popularny", "portal", "posilek", "potega", "powazny", "poziom", "pozytywny",
  "pracownik", "praktyczny", "precyzyjny", "przewodnik", "przyjaciel",
  "przyjazny", "pudelko", "pustynia", "pytanie", "racjonalny", "radozny",
  "rakieta", "realny", "rekin", "restauracja", "robot", "rodzina", "rozsadny",
  "rower", "rozumny", "rzeka", "rzutnik", "samolot", "sciana", "sekunda",
  "serce", "silny", "sklep", "sloik", "snieg", "socjalny", "solidny", "sowa",
  "spokojny", "sportowy", "stary", "student", "szkola", "szybki", "szczesliwy",
  "szlachetny", "szpital", "sztywny", "tajemnica", "taniec", "techniczny",
  "telefon", "teren", "tlumacz", "twardy", "uczciwy", "uczen", "uczony",
  "udany", "ulica", "uroczy", "warzywo", "wazny", "wektor", "wieczny",
  "wielki", "wiedza", "wiersz", "wiosna", "wlasny", "wodospad", "wolny",
  "wycieczka", "wyjatkowy", "wysoki", "wzorowy", "zabawny", "zdrowy",
  "zielony", "zimowy", "zloto", "znany", "zrozumialy", "zyczliwy",
  "akademia","akcja","aktorzy","aktorka","aktywny","albumy","alergia","alfabet","algorytm","altana",
  "amator","ambasada","ambitny","analityk","aneksja","angaż","angielski","animacja","ankieta","anteny",
  "aparaty","apteka","archiwa","architekt","argument","arkusz","armatura","artyleria","artyzm","asertywny",
  "asystent","atakowy","atrakcja","autobus","autorzy","awaria","azylant","badania","bagaznik","bajcowy",
  "bajerancki","balans","baletka","balonik","balsamy","banalny","bandyta","bankiet","baranek","bariera",
  "barista","barkada","barwa","basenowy","bastion","batonik","bazaary","bazarek","bazowy","bednarka",
  "bezpieczny","bialy","biblioteka","biedronka","biegacz","biegowy","bielizna","bierny","biesiada","biletowy",
  "biologia","biurowy","biznes","blaszany","blizszy","blizniak","blokada","blokowy","blondyn","bluzy",
  "bohater","bojownik","bokser","bolesny","bombowy","bonanza","bordowy","borowik","botanik","bractwo",
  "brama","bransoletka","bratnia","braziowy","brelok","breloczki","broszura","brudny","brukselka","bruzda",
  "brzegowy","brzoskwinia","brzydota","budowa","budynek","budzet","bufetowy","bukiety","bulion","bulwar",
  "burakowy","burmistrz","butelka","butikowy","bystry","calosciowy","calownik","camper","capstrzyk","celownik",
  "cement","centralny","ceremonia","certyfikat","charyzma","chemiczny","choroba","chorwacki","chrupki","chustka",
  "chwytak","ciekawy","cieplice","cieplutki","cierpliwy","cieszacy","ciasteczko","ciastkarnia","ciasto",
  "ciemnosc","ciemny","cieszyn","cmentarz","cnotliwy","cokolwiek","colaowy","cudowny","cukiernia","cukierek",
  "cukrowy","cwelunek","czynnik","czynszowy","czytanie","czytelnik","czystosc","czysty","czworka","dagmara",
  "daleki","darmowy","dawny","debatancki","debetowy","decyzja","definicja","deficyt","delegacja","delikatny",
  "demon","denaturat","departament","dermatolog","detaliczny","detektor","diagram","dialog","diagnostyka",
  "diament","dieta","dilerek","dinozaur","diodowy","diplomata","diodowy","dodatni","dodatek","dokument",
  "dokladny","doktorat","doladowanie","dolarowy","dolina","domator","domowy","dominacja","doplyw","doradca",
  "dorosly","dostawa","dostepny","doswiadczony","dotkliwy","dotykowy","dowcipny","dowodca","dozownik","drogeria",
  "drogowy","drobinka","drogocenny","druzyna","drwal","drzemka","dudnienie","duetowy","duchowy","dumny",
  "duszpasterz","dworzec","dyrektor","dyskietka","dyskoteka","dyskusja","dywanowy","dyzurny","dzbanek",
  "dzieciaki","dzieciol","dzielnica","dzielny","dzieńnik","dzienny","dziennik","dziewczyna","dzikowy","dzisiaj",
  "dzwonek","dzynksy","ekipa","ekolog","ekranowy","ekspansja","ekspedycja","ekspres","ekstremalny","ekstrakt",
  "ekwiwalent","elektryk","elektron","elektronika","element","elewacja","elficki","elitarny","emerytka","emocja",
  "empatia","energia","energiczny","enklawa","epilog","epoka","estetyka","etykieta","etyczny","fabryka","faktyczny",
  "fajerwerki","fajny","faksowy","faktura","falownik","fantazja","farbownik","farmacja","fasolka","fastfood",
  "faworyt","federacja","felieton","ferie","festival","figurant","figurka","filologia","filozofia","filmowy",
  "filtrowy","finanse","finezja","firma","fiskalny","fitness","flaga","flakonik","flaming","flanela","flota",
  "flotowy","fluwialny","fokus","foliowy","fonetyka","forma","formularz","forteca","fortuna","fosforyt","fotograf",
  "fotografia","francuski","frankowy","fryzjer","frytura","fucha","fundacja","fundament","funkcja","furmanka",
  "futbolowy","futerał","futurystyczny","gabinet","gadzet","gajowy","galaktyka","galaretka","galeria","galowy",
  "ganek","garażowy","garmazerka","garnitur","gasiwo","gazetowy","gazownia","gazowy","generator","genialny",
  "geografia","geolog","geometryczny","gestosc","gimnazjum","gitary","gitarzysta","gladki","glazura","gleboki",
  "globalny","glodny","glorious","glosnik","glowny","glukoza","gniazdko","gniewny","gofrowy","gojnik","golas",
  "golfowy","gombrowicz","gondola","goniec","gospodarz","goscinny","gotowka","gotowy","grawer","graficzny",
  "grafika","granatowy","granica","gratis","grazyna","grecki","groszowy","groteska","grozny","gruba","gruby",
  "grudniowy","grupa","gruzowy","gryfowy","grywalny","gryzaki","gryzak","gryzienie","grzybnia","gryzmoł",
  "gwarowy","gwiazdor","gwiezdny","gwintowy","habilitacja","hakerzy","halinka","hamburger","handel","handlowy",
  "haniebny","harmonia","harcerz","hartowany","hebanowy","herbata","herbownik","heroiczny","historia","historyczny",
  "hobby","hodowla","hojny","hojrak","holownik","homologacja","horyzont","hotelowy","humor","husaria","hurtownia",
  "idealny","ideowy","idiomatyczny","idolowy","igielnik","iglasty","iglowy","igluowy","ignorant","ikona",
  "iloczyn","iluminacja","imadlo","imigracja","impreza","improwizacja","indeks","indykcja","inercja","infantylny",
  "informatyk","informacja","infrastruktura","ingenieria","ingres","inicjacja","inkubator","inny","insekty",
  "inspektor","instalacja","instancja","instrukcja","instrument","interfejs","internet","interpretacja","interwał",
  "intuicja","inwentarz","inwestor","ironia","istnienie","istotny","jablkowy","jadlodajnia","jagodowy","jajecznica",
  "jakosciowy","jarmark","jasnosc","jasny","jednostka","jedwabny","jedzenie","jezdziec","jezioro","jezykowy",
  "jogurtowy","jonowy","jubilat","jubilerski","judoka","jurorzy","jurysdykcja","jutrzenka","kabaret","kabina",
  "kable","kabriolet","kacikowy","kaczkowy","kalendarz","kaloryfer","kaloryczny","kaloszowy","kamera","kamienica",
  "kamienny","kamizelka","kampania","kanapa","kanapka","kanclerz","kandydat","kanion","kanister","kapsel",
  "kapitan","kaplica","kaprys","karafka","karawana","kardigan","kariera","karminowy","kartonik","kartonowy",
  "kasaory","kaseta","kasjerka","katalog","katastrofa","kategoria","katoda","katolik","kawiarnia","kaznodzieja",
  "kebabowy","keczupowy","kierunek","kierowca","kieszonka","kijanka","kilogram","kilometr","kineskop","kino",
  "kioskowy","kipiel","kisielowy","klamka","klarnet","klasa","klasyczny","klawiatura","klejony","klejnot","klemens",
  "klient","klikacz","klimat","klinika","klonik","kloszowy","klubowy","klockowy","klocki","klozetowy","kluczowy",
  "kmiot","knajpka","kociarek","kociol","kocykowy","koder","kolacja","kolega","kolejka","kolekcja","kolorowy",
  "kolumna","komedia","komendant","komentarz","komfort","kominek","komisja","komitet","komora","kompas","kompletny",
  "komputer","koncert","kondycja","konduktor","koniec","konkurs","konsola","konspekt","kontakt","kontener","kontrola",
  "kontrakt","kontrast","konwersja","kopytko","korale","koralik","korona","koronny","korporacja","korytarz","kosciol",
  "kosmetyk","kosmos","kostium","kostrzyca","koszula","koszyk","kotlina","kotek","kotlet","kowal","kozak","koziol",
  "kradziez","krajowy","kraina","krakers","kranowy","krasnal","krauz","kreator","kreatywny","kredens","kredowy",
  "kredyt","kreskowy","kreskowka","krewetka","krochmal","krokodyl","krokus","kruchy","krucjata","kruszony","krwisty",
  "krysztal","kryterium","kryminal","krzeslo","krzewina","krzykacz","krzywy","ksiaze","ksiadz","ksiazka","ksiestwo",
  "kultura","kumpel","kunktator","kupiony","kupiec","kurnik","kursanta","kursowy","kurtyna","kwiaciarnia","kwiatowy",
  "ladownia","ladunek","ladny","lakier","lakiernia","lakoniczny","lambada","lament","lampion","lamusowy","lanowy",
  "lapacz","lapsus","laptop","lazienka","lekarz","lekcja","lekki","lekowy","leksykon","lenistwo","leniwiec","lepszy",
  "lesniczy","lesnictwo","letnisko","lewarek","lezakowy","licencja","licznik","liczbowy","liderzy","liliowy","linie",
  "linijka","linkowy","listopad","listonosz","litera","literka","lizakowy","lodowka","lodowy","logiczny","logistyka",
  "lokacja","lokalny","lokator","lokomotywa","losowy","losowanie","lotnisko","lotniczy","lozka","lubiany","lubinski",
  "luksus","lusterko","lustrzany","lutownik","luzacki","luzny","lysecki","lyzeczka","lzywy","macierz","machina",
  "magazyn","magiczne","magistrat","mahonowy","majster","makaron","makieta","malarz","malina","malowanie","malpka",
  "maluch","malzowina","manekin","mankiet","manualny","maraton","marchew","margines","marina","marketing","markiza",
  "marmur","marzenie","masarnia","maslo","masowy","maszyna","material","matematyka","matowy","matura","medalowy",
  "mediana","medyk","medycyna","melodia","menedzer","meniszek","mentor","menueta","metalowy","meteor","metoda",
  "metrowy","mialki","miasto","miasteczko","miarka","miazga","miecznik","miednica","miejski","miejsce","miejscowy",
  "mielony","mieszanie","mieszkanie","mieszkaniec","miglanc","migrena","mijanka","mikrofon","mikser","milejowy",
  "miliony","milosc","milutki","mleczarz","mleczny","mleczko","mlewnik","mlynek","mnich","mobilny","modaowy",
  "modelka","modemowy","modlitwa","modowy","modrzew","mokra","mokradla","molowy","moment","moneta","monitor",
  "montaz","moralny","morena","morenowy","morowka","morze","mosiezny","mostowy","motocykl","motylowy","mowa",
  "mrowisko","mrowka","mrozowy","muzyka","muzealny","muzeum","mysliwy","myszkowy","nabrzeze","nagroda","najemca",
  "najmilszy","najszybszy","naklejka","nalezyty","nalewka","nalotowy","namietny","naparstek","napedowy","napiwek",
  "napojowy","naprawa","narciarz","narodowy","narracja","nasiono","nastepny","nauczyciel","naukowy","nautica",
  "nawigacja","nawiew","nawozowy","nektar","neutralny","niemoc","niemowlak","niebieski","niechetna","niechluj",
  "niedziela","niezly","niklowy","niski","niszowy","nocleg","nocny","nozykowy","nosidelko","nosnik","notatnik",
  "nowoczesny","nowina","noworodek","numeralny","numerowy","nutella","obiadek","obiekt","obiektywny","oblicze",
  "obnizka","obornik","obowiazek","obozowy","obrazy","obrazek","obroza","obrotowy","obrusik","obsluga","obszar",
  "obudowa","obuwie","obwod","obyczaj","ocalenie","ochrona","ochotnik","ocynk","odcinek","oddech","oddzial",
  "odejscie","odkurzacz","odkrywca","odlew","odlotowy","odmiana","odnawialny","odpis","odporny","odrzutowiec",
  "odtwarzacz","odwaga","odwiedziny","odwrot","ognisko","ogorek","ogromny","ogrodnik","ogrodowy","ohydny","okazja",
  "okiennica","okladka","okoliczny","okolica","okres","okreslenie","okropny","okrutny","okulary","okularnik",
  "olejarka","olejowy","olimpiada","oliwkowy","olsniewajacy","omaszczenie","omletowy","operacja","operator",
  "opinia","opiekacz","opiekun","opalony","opaska","opcja","oplaty","oplot","opornik","opowiesc","oprawa","oprogramowanie",
  "optymalny","optystyk","opusty","oranzeria","organizacja","organy","orzechy","orzelek","osiadly","osiagniety",
  "osiedle","oslonka","osobisty","osoba","osprzet","ostateczny","ostryga","ostry","oswietlenie","otoczenie","otwarty",
  "owijarka","owocowy","ozdobny","ozdoba","ozonator","pacjent","paczka","paczkarnia","pajaczyk","pakiet","pancerz",
  "pandemia","panorama","pantofel","papier","paragon","parasol","parkiet","parowiec","parowy","partner","parter",
  "partia","paryski","pasazer","pasja","pasnik","pasowy","passtart","pastelowy","pasztet","pasywny","patelnia",
  "patent","patyczek","pawilon","pechowy","pedagog","pedalowy","pegazus","pejzaz","peleryna","pelikan","pelny",
  "pelzacz","pendrive","pensjonat","pepitka","perfumy","pergola","perkusja","peronowy","perspektywa","pestkowy",
  "piecuch","piekarnia","piekny","pielucha","pieniadze","pienny","pierogi","pierwiastek","pierwszy","piewca","pigment",
  "pijarska","piknik","pilarka","pilotowy","piramida","piratka","pisanka","pisarka","pistacja","piszczel","pistolet",
  "pizama","plafon","plakat","planeta","planowy","plaster","plastik","platnik","platowy","plazowy","plecak","plemien",
  "plemienny","plewowy","pleziony","pliktowy","plotka","plotkowy","plowienie","plucnica","pluton","plytowy","plywanie",
  "pobierak","pobocze","pochmurny","pochodnia","pochwa","pociag","pociecha","pocisk","poczatek","poczta","poczucie",
  "podatek","podatny","poddasze","podejscie","podloga","podroz","podrecznik","podstawowy","podsumowanie","poduszka",
  "podwozie","pogoda","pogodny","pojedynek","pojnik","pokarm","poklad","pokojowy","pokolenie","pokrowiec","pokusa",
  "polaczek","polarna","polarnik","polarnik","polerka","poligon","polityka","polny","polokrag","polowanie","polski",
  "poltora","poludnie","pomidor","pomocnik","pomocny","pomost","pompa","poniedzialek","ponczo","popularny","populacja",
  "porecz","porcja","porozumienie","portfel","portal","portier","portowy","porwanie","posagowy","posilek","poslanie",
  "poslowie","postawa","postep","postoj","postura","posypka","potega","potencjal","potrawa","potworny","powazny",
  "powiat","powietrze","powitanie","powoz","poziom","pozyczka","pozytywny","poznanie","pozorny","pozostały","pracownik",
  "praktyczny","pralka","prasa","prasowacz","prawdziwy","prawy","prayer","precyzyjny","preferencja","pregierz",
  "premiera","prenumerata","prezent","profil","profesor","program","projekt","projektor","prolog","promocja","promyk",
  "pronomen","proporcja","prostownik","prosty","prowincja","prywatny","prywatnik","prysznic","przeciwnik","przedmiot",
  "przedzial","przedpokoj","przedrostek","przegrana","przeglad","przejazd","przejscie","przekaski","przelacznik",
  "przelot","przemiany","przemoc","przenosny","przepisy","przeplyw","przerwa","przesylka","przeszkoda","przestroga",
  "przewodnik","przewoz","przybory","przyczyna","przyjaciel","przyjazny","przyklad","przymiotnik","przyneta","przyroda",
  "przysmak","przytomny","przytulny","przywodca","przywykly","psikusy","psychiatra","psycholog","ptaszek","publiczny",
  "pudelko","pudernik","pudel","pudrowy","pustynia","pusty","pytanie","racjonalny","radosny","radzimy","rafineria",
  "raglan","rajstopy","rakieta","ramowka","ranking","raperzy","raport","rasowy","ratownik","realista","realny",
  "rebusik","recenzja","redaktor","reduta","reflektor","reforma","region","rejestr","rekawica","rekinek","rekord",
  "rekrut","relacja","relaks","remedium","remont","renoma","repertuar","rezerwacja","rezydent","rezyser","rezyseria",
  "rękawnik","riksza","ringu","robotnik","roboczy","robustny","rodak","rodzaj","rodzina","rogalik","rokowania",
  "rolnik","rolowanie","romans","rondowy","rosolina","rosyjski","rotacja","rower","rozeta","rozgwiazda","rozklad",
  "rozmowa","rozpiety","rozsadny","roztargniony","rozum","rozumny","rozwoj","rozyczka","ruchomy","rudowlosy",
  "rudyment","ruletka","rumianek","ruraowy","rusztowanie","rzeka","rzeczowy","rzeszowy","rzutnik","sadownia","sadownik",
  "saganek","sakiewka","saksofon","salaterka","salonowy","salowa","samolot","samotnik","sampel","sandomierz","sandomierski",
  "sandwich","saperka","sardynka","sarenka","sarkazm","satelita","satyra","scena","scienny","sciana","scigacz",
  "sciskacz","seansowy","sedesowy","segment","sekret","sekretarz","sekunda","seledyn","semafor","senator","sentyment",
  "serce","sernik","serwisy","serwisy","serwis","serwerek","serwetka","serwisowy","seryjny","serwus","sesyjny",
  "setkowy","siadanie","siadlom","siedziba","siedzenie","sielski","sierpien","siedziba","sigma","silacz","silnik",
  "silowy","silownia","siniak","siniaki","siodlo","siostra","sitarz","sitowie","skala","skarbnik","skarby","skarpeta",
  "skarpetki","skarzacy","skazaniec","skeczowy","sketchup","sklad","skladnik","sklep","sklepik","sklepowy","sklonny",
  "skocznia","skokowy","skorupa","skorygowany","skorzany","skosny","skotowy","skradziony","skrajny","skrzynka",
  "skrzypce","skrzypek","skrzynkowy","skuter","slabosc","slajdowy","slimak","slomiany","sloneczny","slownik","slubny",
  "slynny","smaczny","smakowy","smarowanie","smaszny","smartfon","smialy","smietana","smieszek","smoczek","smogowy",
  "smolisty","smutek","snajper","snopowy","śniegowy","socjalny","soczewka","sodek","sofaowy","sojowy","sokownik",
  "solidny","solniczka","solowy","somatyczny","sonda","sonet","soniczny","sopel","sosnowy","sowaowy","spacer",
  "spadek","spaliny","sparkowy","sparowanie","spawacz","specjal","specjalny","spedycja","spektryk","sperma","spiewnik",
  "spiker","spinacz","spirala","spisowy","spizarnia","splata","spodnie","spokojny","sponad","sponsor","sporny",
  "sportowy","sprayowy","spray","sprzedaż","sprzet","sprytny","spuszczacz","spychacz","srebrny","stabilny","stadion",
  "stagnacja","stalowy","standard","stanica","stanik","stancja","stary","statki","statystyka","statuetka","stawa",
  "stawowy","stemple","stepowy","sterownik","sterylne","steward","stolik","stolowy","stomatolog","stonoga","stopien",
  "stoper","stopy","strazak","straznik","strata","strategia","strona","strug","strumien","struna","strusel","strzal",
  "strzykawka","studenci","student","studnia","studiowanie","studiowy","stwardnienie","styczniowy","stylowy","subskrypcja",
  "sukienka","suknia","sukulent","sukurs","sumaowy","sundown","supermarket","surowiec","surowy","suszarka","suwakowy",
  "swiadomy","swiatlo","swiatowy","swinia","swistak","szafa","szafran","szalik","szalony","szampon","szarecki","szary",
  "szczegol","szczesliwy","szczupak","szczytowy","szefowa","szeregowy","szermierz","szkolny","szlachetny","szlafrok",
  "szlakowy","sznurek","sznurki","szopka","sztanga","sztorm","sztuka","sztuki","sztylet","sztywny","szuflada","szumowy",
  "szusowy","szwajcar","szynka","szynkowy","szybki","szybowiec","szyfrant","szyldowy","szynobus","tablet","tackowy",
  "taczka","tancerz","taniec","targowy","tarasowy","tarka","tarnina","tasma","tasmy","tasmaowy","tatarak","tatuaz",
  "technika","techniczny","telefon","telewizor","tematowy","temperament","tendencja","tenisista","terenowy","termin",
  "terminarz","termos","terytorium","tesknota","testowy","tkanina","tkankowy","tloczarnia","tloczenie","tloczny",
  "tlumacz","tlumik","tolerancja","tomikowy","tonacja","topazowy","topielec","torfowy","torowisko","tortowy","towarek",
  "towarowy","traktor","tramwaj","trampki","transmisja","trener","trening","triumf","trofeum","tropikalny","trucizna",
  "trumna","trunek","truskawka","trwale","trzaska","trzeci","tubaowy","tucznik","tulipan","tulipany","tulowy","turysta",
  "twardy","tworczy","tygodnik","tygrysi","tylni","tysiaj","uczciwy","uczelni","uczen","uczony","ucztowanie","uderzenie",
  "ugotowany","ujecie","ujscie","ujscowy","uklad","ukojenie","ulubiony","ulica","ulotkowy","ulubione","umeblowanie",
  "umiejetnosc","umowa","umyslowy","unijny","unikalny","uniwersytet","uparty","upiorek","uprawa","uprzejmy","upustowy",
  "urazowy","urbanski","urbanistyka","uroczysty","uroczy","urodziny","urzednik","urzadzenie","urzad","usluga","usmiech",
  "usuwanie","utrata","utrzymanie","uwaga","uwazny","uzalezniony","uzdrowisko","uznanie","uzwojenie","wabikowy","wada",
  "wagonowy","wahadlo","wakacje","walizka","walowy","walcarka","walec","walor","wampir","wanna","wapienny","warcaby",
  "warunki","warzywo","wazny","wedkarski","wektor","welurowy","wentylacja","weranda","werbunek","wesele","wesoly",
  "wesolutki","wesolosc","wespolek","westchnienie","weteran","wezlowy","wiazar","wibracja","wibrator","wichura","wieczor",
  "wieczny","wiekowy","wielki","wieszak","wietrzny","wiezowiec","wiezien","wigilia","wiktoria","wilczur","willa",
  "wilgotny","winaowy","winny","winogrono","winylowy","wiosenny","wioska","wioslarka","wirnik","wisior","witaminy",
  "witraż","witryna","wizaowy","wizjer","wizualny","wkladka","wklad","wkladowy","wkladka","wklejka","wkladany","wlosian",
  "wloski","wlosowaty","wloszczyzna","wloczykij","woda","wodnik","wodociag","wodorowy","wodospad","wojenny","wojewoda",
  "wojskowy","wokol","wolfram","wolny","wolta","wolumen","woreczek","workowy","woskowy","woskowina","wotum","wowczas",
  "wpisowy","wplywowy","wplyw","wprowadzanie","wspieranie","wspolnota","wspolny","wstazka","wsteczny","wtrysk",
  "wybieg","wyborca","wyborowy","wybrany","wybuchowy","wycinarka","wycieczka","wycinka","wycior","wycinowy","wycieraczka",
  "wydanie","wydawca","wyglad","wygodny","wyjatkowy","wykaz","wykres","wykrojnik","wykrojenie","wylot","wylapanie",
  "wyrazny","wyraz","wyrwanie","wyrzutnia","wyslanie","wysoki","wysokosc","wystawa","wystep","wystroj","wysypisko",
  "wytwornia","wywazony","wywoz","wyzwanie","wzmacniacz","wzorek","wzolty","wzrokowy","wzorowy","wzywacz","zabawka",
  "zabawny","zabezpieczenie","zabieg","zabior","zabojczy","zachod","zachowany","zaciag","zacisk","zadanie","zadbany",
  "zadluzenie","zadowolony","zadumany","zagadka","zagadnienie","zaglowa","zagroda","zajazd","zaklad","zaklocenie",
  "zakonczenie","zakret","zakupy","zaleta","zalew","zalesiony","zaloba","zalotny","zamawianie","zamek","zamiana","zamkniety",
  "zamowienie","zamykacz","zanik","zapach","zapadka","zapasowy","zapis","zapisy","zaplaty","zaplecze","zaplon","zapora",
  "zaprawa","zaproszenie","zarazek","zarzad","zarowka","zarzut","zasada","zasieg","zasilanie","zasilacz","zaskroniec",
  "zastepca","zastrzyk","zasuwka","zasyp","zatoka","zatrudnienie","zatwierdzenie","zawartosc","zawodnik","zawodowy",
  "zazdrosc","zbawienny","zbiorki","zbiornik","zbiorowy","zbliżenie","zbroja","zbrojny","zbrojenie","zbrojownia",
  "zbrodniarz","zebranie","zegarek","zegarmistrz","zielony","ziemniak","ziewanie","zjawisko","zlacze","zlazenie",
  "zlomiarz","zlomowisko","zloto","zlotowy","zmarszczka","zmiana","zmyslowy","znacznik","znajomy","znakowy","znany",
  "zniczowy","zniewolenie","zrozumialy","zupaowy","zuzlowy","zwariowany","zwiazek","zwiedzanie","zwolnienie","zwrot",
  "zyczliwy","zyrafa","zywieniowy","zywioł","zywiolowy","zywnosc","zywnosciowy","zyskowny","zytniak","zywiciel"
];
